services:
  uix:
    command: ["./cli", "dev"]
    build:
      context: ./uix
    volumes:
      - ./uix:/app
    ports:
      - 80:80
    environment:
      - API_URL=http://localhost

  # api:
  #   command: ["./cli", "dev"]
  #   build:
  #     context: ./api
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - 81:80
  #   environment:
  #     - APP_HOST=localhost
  #     - ASSETS_URL=http://localhost/
